name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
    branches:
    - '**'
    tags:
    - '*.*.*'
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.302

      - run: dotnet --info

      - name: Build and Publish
        shell: bash
        env:
            NUGET_URL: https://www.myget.org/F/augustoproiete/api/v3/index.json
            NUGET_URL2: https://www.myget.org/F/augustoproiete/api/v2/package
            NUGET_API_KEY: ${{ secrets.MYGET_CI_AUGUSTOPROIETE_API_KEY }}
        run: |
          # Restore .NET tools
          dotnet tool restore

          # Get the version number
          VERSION=$(dotnet minver --tag-prefix v --verbosity error --default-pre-release-phase preview)
          echo version=$VERSION

          # Run the build script
          dotnet cake --target="publish" --packageVersion="$VERSION"

      - name: Artifacts
        uses: actions/upload-artifact@v2.1.1
        with:
          name: artifacts.zip
          path: build/packages/**/*.nupkg
