name: CI

on:
  push:
    branches:
    - master
    - release-*
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    runs-on: windows-2016

    steps:
    - name: Get the source code
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Run a one-line script
      run: echo Building!

    - name: Run a multi-line script
      run: |
        echo Building
        echo ........
