name: build

on:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Deploying!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Deploying
        echo ..........
